### PR TITLE
Feat/plmg-card

### PR DESCRIPTION
**Pull request by JakeH91**
Closes: [DEVELOP: Card](https://app.asana.com/0/1200489836971088/1201799627233605)

- add Card component
- add storybook stories
- add accessibility tests
- add spec tests
- add React example

I've also added the relevant documentation to Zeroheight. I'll update it with Storybook's links when the PR is merged.

### CODE REVIEW

**Comment by JakeH91** [comment]
Oops I forgot storybook stuff, ok this isn't finished

**Comment by TanguyDucky** [comment]
GitHub checks will be happy once https://github.com/DuckyTeam/Plumage/pull/33 is merged

**Comment by TanguyDucky** [comment]
This is ready for review, waiting for an answer from the designer reagarding `min-width` and `max-width`

**Review by TanguyDucky — APPROVED** [review]
Waiting for designers QA

**Pull request merged**
