### PR TITLE
Feat/slider

### PR DESCRIPTION
**Pull request by jamesducky**
Closes[https://app.asana.com/0/1198920871936085/1201854443860291/f]

### Summary of changes included in this PR

- Implementation of plumage tooltip component [figma](https://www.figma.com/file/4ZukYZAMHrsCIsrZu9u2a6/Plumage-Components?node-id=158%3A37908).

### Known Issues
- Focus state does not trigger required outline. Suspect cause is use of native input HTML range slider with default styles states overridden. Problems likely caused by &::-webkit-slider-thumb. 
- Hover and Active states creating square outlines in Safari.
- e2e tests failing when mapping over tick marks and tick labels.

### Reviewer checklist:

- Tests for
  - accessibility
  - rendered HTML (spec)
- Storybook stories for all variants
- JSDoc documentation for component
- Update Example app (React, ...)

### CODE REVIEW

**Review by nathan-bird — CHANGES_REQUESTED** [review]
Through component testing I identified some functionality issues:

- [ ] Input allows values greater than the range. This causes the slider width to expand and (if shown) the thumb label to appear off of the scale.
Screenshot 2022-06-05 at 14 34 03

- [ ] Input allows values lower than the range. This causes the slider width to expand and (if shown) the thumb label to appear off of the scale.
Screenshot 2022-06-05 at 15 08 18

- [ ] Removing the input value causes the thumb to loose styling. Also occurs when entering a non-numeric character such as a dot. 
Screenshot 2022-06-05 at 14 35 53
Screenshot 2022-06-05 at 14 39 36

- [ ] Input field allows any size value, including decimals. This can cause storage or arithmetic issues if not controlled.    
Screenshot 2022-06-05 at 14 38 52

- [ ] On a marks and steps slider entering a value between to two marks/steps in the input field causes inconsistent track and thumb behaviour.
Screenshot 2022-06-05 at 14 41 32
Screenshot 2022-06-05 at 14 43 25

- [ ] The thumb label is not centered on the thumb as it travels across the track.
Screenshot 2022-06-05 at 14 46 22Screenshot 2022-06-05 at 14 45 54Screenshot 2022-06-05 at 14 47 51

- [ ] A max value greater than 4 numbers overflows into the input field and is not readable in the input field  
Screenshot 2022-06-05 at 14 51 36
 
- [ ] Mark values greater than 1 number are not centered. This causes visual misalignment of the thumb and thumb label.
Screenshot 2022-06-05 at 14 59 46

- [ ] Mark values may overflow
Screenshot 2022-06-05 at 14 58 41

**Comment by jamesducky** [comment]
> Through component testing I identified some functionality issues:
> 
> * [x]  Input allows values greater than the range. This causes the slider width to expand and (if shown) the thumb label to appear off of the scale.
> 
> Screenshot 2022-06-05 at 14 34 03
> 
> * [x]  Input allows values lower than the range. This causes the slider width to expand and (if shown) the thumb label to appear off of the scale.
> 
> Screenshot 2022-06-05 at 15 08 18
> 
> * [x]  Removing the input value causes the thumb to loose styling. Also occurs when entering a non-numeric character such as a dot.
> 
> Screenshot 2022-06-05 at 14 35 53
> 

Resolved by controlling input. Input field rejects
- empty strings
-

**Comment by jamesducky** [comment]
> Through component testing I identified some functionality issues:
> 
> * [x]  Input allows values greater than the range. This causes the slider width to expand and (if shown) the thumb label to appear off of the scale.
> 
> Screenshot 2022-06-05 at 14 34 03
>

**Comment by jamesducky** [comment]
> Through component testing I identified some functionality issues:
> 
> * [x]  Input allows values greater than the range. This causes the slider width to expand and (if shown) the thumb label to appear off of the scale.

> 
> Screenshot 2022-06-05 at 14 34 03
> 
> * [x]  Input allows values lower than the range. This causes the slider width to expand and (if shown) the thumb label to appear off of the scale.
> 
> Screenshot 2022-06-05 at 15 08 18
> 
> * [x]  Removing the input value causes the thumb to loose styling. Also occurs when entering a non-numeric character such as a dot.
> 
> Screenshot 2022-06-05 at 14 35 53
> 
> Screenshot 2022-06-05 at 14 39 36
> 
> * [x]  Input field allows any size value, including decimals. This can cause storage or arithmetic issues if not controlled.
> 
> Screenshot 2022-06-05 at 14 38 52
> 
> * [x]  On a marks and steps slider entering a value between to two marks/steps in the input field causes inconsistent track and thumb behaviour.
> 
> Screenshot 2022-06-05 at 14 41 32
> 
> Screenshot 2022-06-05 at 14 43 25
> 
> * [ ]  The thumb label is not centered on the thumb as it travels across the track.
>   Screenshot 2022-06-05 at 14 46 22Screenshot 2022-06-05 at 14 45 54Screenshot 2022-06-05 at 14 47 51
> * [ ]  A max value greater than 4 numbers overflows into the input field and is not readable in the input field
> 
> Screenshot 2022-06-05 at 14 51 36
> 
> * [ ]  Mark values greater than 1 number are not centered. This causes visual misalignment of the thumb and thumb label.
> 
> Screenshot 2022-06-05 at 14 59 46
> 
> * [ ]  Mark values may overflow
> 
> Screenshot 2022-06-05 at 14 58 41

Resolved 
- Input field is now controlled. Value is not updated until after validation. Values can only be selected from a list. This resolves most issues.

Unresolved
- Alignment issues persist. This is caused by the use of the native slider which creates unpredictable styling. Previous attempts at compensating with workarounds that obscured but did not resolve this issue. It may be necessary to replace the native slider with a custom built one.

**Review by nathan-bird — COMMENTED** [review]
The slider looks to be ok but I am wondering about how it will function in a real example. How will the app handle changes on the slider? Could you flesh out the example app to show submitted values and real time slider values in the app.

**Comment by nathan-bird** [comment]
Closing this PR in favour of a new [reverted branch](https://github.com/DuckyTeam/Plumage/tree/feat/slider-revert) to remove breaking changes to the component.

**Pull request closed without merging**
